//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ChatAdministrator
{
    public int Id { get; set; }
    public int GroupChatId { get; set; }
    public int UserId { get; set; }
}

public partial class Comment
{
    public int Id { get; set; }
    public string EmailAddress { get; set; }
    public string CommentInformation { get; set; }
    public System.DateTime DateAndTimeOfCommentSent { get; set; }
    public Nullable<int> CourseId { get; set; }

    public virtual Course Course { get; set; }
}

public partial class Course
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Course()
    {
        this.Comments = new HashSet<Comment>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string ImageUrl { get; set; }
    public string AdditionalInformation { get; set; }
    public string PartFullTime { get; set; }
    public int LevelOfCourse { get; set; }
    public int SubjectAreaId { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual SubjectArea SubjectArea { get; set; }
}

public partial class Friend
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Friend()
    {
        this.Messages = new HashSet<Message>();
        this.UserLogins = new HashSet<UserLogin>();
    }

    public int Id { get; set; }
    public string FirstName { get; set; }
    public string Surname { get; set; }
    public string DateOfBirth { get; set; }
    public string CurrentStudent { get; set; }
    public string Gender { get; set; }
    public string EmailAddress { get; set; }
    public string PhoneNumber { get; set; }
    public string ProfilePicture { get; set; }
    public int UserId { get; set; }
    public Nullable<int> CourseId { get; set; }
    public Nullable<int> FriendRequest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Message> Messages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UserLogin> UserLogins { get; set; }
}

public partial class GroupChat
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GroupChat()
    {
        this.GroupMembers = new HashSet<GroupMember>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string ProfilePicture { get; set; }
    public int AdministratorId { get; set; }

    public virtual UserLogin UserLogin { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<GroupMember> GroupMembers { get; set; }
}

public partial class GroupMember
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GroupMember()
    {
        this.GroupMessages = new HashSet<GroupMessage>();
    }

    public int Id { get; set; }
    public int FriendId { get; set; }
    public int GroupChatId { get; set; }

    public virtual GroupChat GroupChat { get; set; }
    public virtual UserLogin UserLogin { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<GroupMessage> GroupMessages { get; set; }
}

public partial class GroupMessage
{
    public int Id { get; set; }
    public int GroupMemberId { get; set; }
    public string MessageText { get; set; }
    public System.DateTime DateOfMessageSent { get; set; }
    public System.TimeSpan TimeOfMessageSent { get; set; }

    public virtual GroupMember GroupMember { get; set; }
}

public partial class Message
{
    public int Id { get; set; }
    public Nullable<int> FriendId { get; set; }
    public int UserId { get; set; }
    public string MessageText { get; set; }
    public string PictureInserted { get; set; }
    public string VideoInserted { get; set; }
    public System.DateTime DateOfMessageSent { get; set; }
    public System.TimeSpan TimeOfMessageSent { get; set; }

    public virtual Friend Friend { get; set; }
    public virtual UserLogin UserLogin { get; set; }
}

public partial class SubjectArea
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SubjectArea()
    {
        this.Courses = new HashSet<Course>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string ImageUrl { get; set; }
    public string AdditionalInformation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Course> Courses { get; set; }
}

public partial class UserLogin
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserLogin()
    {
        this.GroupChats = new HashSet<GroupChat>();
        this.GroupMembers = new HashSet<GroupMember>();
        this.Messages = new HashSet<Message>();
    }

    public int Id { get; set; }
    public string FirstName { get; set; }
    public string Surname { get; set; }
    public string DateOfBirth { get; set; }
    public string Gender { get; set; }
    public string EmailAddress { get; set; }
    public string PhoneNumber { get; set; }
    public string CurrentStudent { get; set; }
    public string Password { get; set; }
    public string ProfilePicture { get; set; }
    public Nullable<int> CourseId { get; set; }
    public string Description { get; set; }
    public Nullable<int> FriendId { get; set; }

    public virtual Friend Friend { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<GroupChat> GroupChats { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<GroupMember> GroupMembers { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Message> Messages { get; set; }
}

public partial class WebsiteAdministrator
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string Surname { get; set; }
    public string DateOfBirth { get; set; }
    public string Gender { get; set; }
    public string EmailAddress { get; set; }
    public string Password { get; set; }
    public bool LoggedOn { get; set; }
}
